#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# start with terminal
kitty &

# key bindings
sxhkd &

# wallpaper
$HOME/.config/bin/wallpaper &

# Enable Click
$HOME/.config/bin/AutoClick

# picom
picom -C -b

# panel
polybar main &

# flameshot
flameshot &

# GreenClip
greenclip daemon &

# SmartCharging
SmartCharging &

# start redshift
redshift -t 6500:4600 -l 3.2476811:101.74012689999999 &

# Set some bspc specific stuff
bspc monitor -d I II III IV V VI VII VIII

bspc config border_width 0
bspc config window_gap 0
bspc config top_padding 23
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config focused_border_color "#5c889c"

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod1
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# some window rules
bspc rule -a Typora desktop='^4' follow=on focus=focus=on
bspc rule -a TelegramDesktop desktop='^3' follow=on focus=focus=on
bspc rule -a Brave-browser desktop='^2' follow=on focus=on
bspc rule -a feh state=floating follow=on
