#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# try to start termite in the first place
kitty &

# key bindings
sxhkd &

# wallpaper
wallpaper &

# xfce settings
xfsettingsd &

# picom
picom -C -b

# panel
polybar main &

#dunst
dunst &

#flameshot
flameshot &

# start libinput-gestures
#libinput-gestures-setup start

# start redshift
redshift -t 6500:4600 -l 3.2476811:101.74012689999999 &

# rofi greenclipboard daemon
#greenclip daemon &

# Set some bsp specific stuff
bspc monitor -d I II III IV V VI

bspc config border_width 0
bspc config window_gap 3
bspc config top_padding 26
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config border_radius 5

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod1
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# some window rules
bspc rule -a Brave-browser desktop='^2' follow=on focus=on
bspc rule -a Spotify desktop='^8' follow=on focus=on
bspc rule -a feh state=floating follow=on
bspc rule -a vlc desktop='^0'

#some dumbshit i have no idea wtfk is this
xmodmap -e 'keycode 117='
