#!/bin/bash

current_date=$(date | awk '{print$2" "$3}')

if [ -z $1 ]; then
	read -p "What you want me todo: " input
	if [ $input == open ]; then
		cd ~; cd Notes; ls
	elif [ $input == today ]; then
		cd ~; cd Notes;
		file_name=$(ls -lt | awk '{print$9}' | grep $current_date)
		echo $file_name

	fi
fi
if [ ! -z $1 ]; then
nano ~/Notes/"$1".tt 
fi
#Still nothing new 
